### ISSUE TITLE
constant refreshing, restarting local client and PC did not fix

### ISSUE THREAD

**Issue by M1ghtyboyPersonal** [FoldingAtHome/fah-web-client#18]
nothing seems to be causing this apart from inactivity. I have been unable to look at web control for 2 days now. It doesn't even load the information before it refreshes again.

**Comment by rdwyman** [comment]
If I were a betting man I'd guess you were using Chrome. Is that true? Try it in Edge and I bet the problem goes away. I believe this is related to a [security issue](https://www.reddit.com/r/Folding/comments/674i9j/web_client_constanty_reloading/) in Chrome. If I'm right, Folding@Home should be updated to serve the client over HTTPS. There might be technical reasons why this can't be done.

**Comment by M1ghtyboyPersonal** [comment]
using chromium edge

**Comment by talregev** [comment]
Also vote for:
"constant refreshing, restarting local client and PC did not fix"
I am using windown 10 64bit. also in the first time the web client is working.
After close and re-open constant refresh.

**Comment by rdwyman** [comment]
[Here](https://stackoverflow.com/a/53388534) is a possible fix. I'd white list `https://client.foldingathome.org/`. I don't know if this will work in Edge even though it is now chromium based so testing in Chrome itself might make more sense. If this resolves the issue, then we would at least have an idea as to what was going on. I'd test it myself right now but my brain is melting due to lack of sleep. I might try it tomorrow. I'd be interested to see if you guys have any luck with it.

**Note that there is a good chance I'm sending us up the wrong tree!** In Chrome I just noticed every refresh is producing a 404 error which might mean this isn't a security thing.

**Comment by AkshayRao27** [comment]
I have the same issue as well. Chrome has a refresh loop when trying to access the web control. However, the web control works just fine in Chrome's incognito mode. It might have something to do with the browser cache / cookies.

**Comment by LayneTheEpic** [comment]
I have the same issue with the restarting loop in Chromium Edge, use Firefox if you can. It doesn't happen there.

**Comment by jcoffland** [comment]
This is a duplicate of #6.

**Comment by WebMaximus** [comment]
> I have the same issue as well. Chrome has a refresh loop when trying to access the web control. However, the web control works just fine in Chrome's incognito mode. It might have something to do with the browser cache / cookies.

Considering clearing the cache and doing a hard reload fixes the issue, I'd say what you suggest being a cache issue seems quite likely!
