### ISSUE TITLE
stop and finish a work unit not working

### ISSUE THREAD

**Issue by informatorius** [FoldingAtHome/fah-web-client#2]
The Advanced Control has 3 options in the Status tab: Fold, Pause, and Finish. However, the Web Control Stop and Finish functionality is not working.

If the FAHClient is paused, then the Web Control will have a Start Folding button, which behaves like the Advanced Control's Fold button. If the FAHClient is folding, then the Web Control shows shows a Stop Folding button. 

Clicking on it makes a window appear with 2 more buttons: "Finish up, then stop" and "Stop now". 
1) "Stop now" behaves like the Pause button. => OK
2) "Finish up, then stop" simply closes the window, just like the X in the corner of the window. It does not behave like Finish. => Not OK

**Comment by andyhardy** [comment]
Web Control "Finish up, then stop" still doesn't appear to work on Version 7.5.1 running on Windows 10.

Selecting "Finish up, then stop" does not stop the process when the current work unit(s) complete and does not prevent new unit(s) from being downloaded and worked on.

**Comment by informatorius** [comment]
Looks like to be an issue with FahClient which should on "Finish": Stop running downloads of new work units and pause idle slots.

**Comment by PantherX** [comment]
Is this still in issue with V7.6.13?

**Comment by madisx** [comment]
Finish up and then stop button has no action bound to it in the code. It just closes the modal and does not send out any request to the API.
```javascript
$('#stop-popup .cancel').on('click', function(e) {
        e.preventDefault();
        $('#stop-popup').dialog('destroy');
    });
```
Would create a pull request, but not familiar with the API, so I don't know what request needs to be made to trigger "finish".

**Comment by informatorius** [comment]
@madisx: Thank for looking into this. Your method is not the finish or stop action but is the cancel of the finish or stop dialog. That is why it only destroys the dialog.
![grafik](https://user-images.githubusercontent.com/6989214/83753065-e14e3f80-a669-11ea-9fc1-cf05131c2632.png)

**Comment by madisx** [comment]
Well then there is some mixup with the classes, as "Finish up" button has cancel class as well:
![cancel](https://user-images.githubusercontent.com/2912555/83753873-bc5eca00-a673-11ea-9017-7af5ea4b7725.png)

**Comment by apraetor** [comment]
> Looks like to be an issue with FahClient which should on "Finish": Stop running downloads of new work units and pause idle slots. Issue only happens when an idle slot is waiting for a new work unit. Because it is not running yet then it does not get to state finish. Instead it stays idle - and can get a new work unit later unexpectedly. It is a rare case because most of the time slots should be running or switching to new work unit. But with server overload it happens more often.

Found this report after witnessing this myself. CPU WU was ~50% complete, GPU was idle due to a lack of WUs. I clicked "finish" in the Advanced Control UI and returned later to find the CPU slot "Paused:finished" while the GPU slot was "Finishing". Definitely not the behavior I expected, for it to download a WU after I clicked "Finish". 

Shouldn't any slot in "Idle" state immediately switch to "Paused:finished" in this case?

**Comment by jeremyn** [comment]
In my case clicking "Finish up, then stop" does nothing but close the modal. It's not a rare edge case that only happens when things are in some particular unlikely state, instead the button simply appears to do nothing but close the box.

Anyway if you're using the web client because the advanced control isn't available for you and are hitting this bug and don't know how to gracefully end your processing, here are two workarounds to "finish" your work units. When done correctly the work units in the web client should change to say "Finishing" and the circles should be yellow with spinning arrows inside.

Option 1: on the running system, `telnet localhost 36330` should bring you to a `Welcome to the FAHClient command server.` prompt. The `finish` command moves all units into the "finishing" state. The `help` and `slot-info` commands may also be useful.

Option 2: run the `FAHClient` executable with the `--send-finish` option, for example: `/usr/bin/FAHClient --send-finish`. Do not do this with the `FAHClient` service in `/etc/init.d` or with `service FAHClient` or similar, that is something different.

**Comment by jcoffland** [comment]
It should work if you update your client to v7.6.21.

**Comment by jeremyn** [comment]
@jcoffland I can confirm, I just tried "Finish up, then stop" in a `fah-gpu` v7.6.21 Docker container and it worked as expected. Thanks for pointing that out! I encountered the problem here using the v7.6.8 standard client due to https://github.com/FoldingAtHome/fah-issues/issues/1473 where the old version was recommended as a workaround.
